### ISSUE TITLE
Where is the model file

### ISSUE THREAD

**Issue by Zumbalamambo** [aakhundov/tf-attend-infer-repeat#1]
Where can I find the model file and how do I test it?

**Comment by aakhundov** [comment]
As this is work in progress, it's not well structured yet. To test you should first run multi_mnist.py to generate the dataset from plain MNIST. Then you can run model.py itself, which will generate some reconstruction samples after each 200 iterations and save them in the air_results folder. For the moment, the model doesn't always learn well, but we're working on it.

**Comment by Zumbalamambo** [comment]
im looking for the gender detection model

**Comment by aakhundov** [comment]
Oh, then you need to look into other repository [here](https://github.com/aakhundov/deep-german). One trained model is in the /results/models folder. You can test it manually by running evaluate.py.

**Comment by Zumbalamambo** [comment]
is it a cnn based model?

**Comment by aakhundov** [comment]
No, RNN-based. Specifically, LSTM-based. I'll probably upload some CNN-based model training code, as well as some trained models soon too.

**Comment by Zumbalamambo** [comment]
ya please... Im looking forward learn to to detect gender real-time using opencv

**Comment by aakhundov** [comment]
I guess, we're talking about different things. Do you mean detecting the gender of a person from an image? Or grammatical gender of a word from its textual form (that's actually what is done in [this project](https://github.com/aakhundov/deep-german))?

**Comment by Zumbalamambo** [comment]
detecting the gender from image

**Comment by aakhundov** [comment]
Sorry, can't help with that :)

**Comment by Zumbalamambo** [comment]
:) thank you
