### ISSUE TITLE
KL divergence for z_pres

### ISSUE THREAD

**Issue by thematrixduo** [aakhundov/tf-attend-infer-repeat#10]
Hi, I am just curious about how do you compute the kl divergence for z_pres in function "concrete_binary_kl_mc_sample". Do you have any theory behind the formula? I am not sure why do you use pre_sigmoid and log_odds rather than the gumbel samples.

**Comment by aakhundov** [comment]
Hi,

As the KL divergence between two Concrete distributions was not available in a closed form, we resorted to one-sample MC estimation of the KL. As for the "pre-sigmoid" and "log-odds", we follow the recommendation from [(Maddison et al., 2016)](https://arxiv.org/abs/1611.00712) "to work with Concrete random variables in log-space" for better numerical stability (cf. section "C.3 WHICH RANDOM VARIABLE TO TREAT AS THE STOCHASTIC NODE" of the Appendix).

Hope this helps!

Best regards,
Adnan.
