### ISSUE TITLE
Gumbel noise samples

### ISSUE THREAD

**Issue by Minyz16** [aakhundov/tf-attend-infer-repeat#11]
Thanks for your great work! I have a question about Gumbel noise. Standard Gumbel noise can be sampled using G = -log(-log(u)), however in the code I find that you're using  log(u)-log(1-u), which is not equivalent. Could you explain it please?

**Comment by Minyz16** [comment]
Oh, after I read the original paper I realized this is a special case for binary case.

**Comment by aakhundov** [comment]
Sorry for the late reaction. Glad you found the answer. Good luck!
