### ISSUE TITLE
Training on multi-mnist with background images

### ISSUE THREAD

**Issue by kshitijd20** [aakhundov/tf-attend-infer-repeat#9]
Hi, 
I just wanted to confirm if you were able to successfully train the model on multi-mnist images with background. When I tried just using the same parameters without background it doesn't work. In one case loss becomes NaN, while in other the model just reconstructs background image without digits.

**Comment by aakhundov** [comment]
Hi,

Unfortunately we didn’t get any satisfactory results while including backgrounds. We tried some experiments (like subtracting a learnable “background” image from every sample before feeding it into LSTM), but they didn’t yield anything interesting. So png-images in the repository and multi_mnist.py’s functionality of including them in dataset generation are there just for completeness. All the stability results that we’ve obtained and reported had been on  zero (black) background data.

**Comment by kshitijd20** [comment]
Thank you for the clarification, I tried something similar but no success yet.
